### PR TITLE
Add CDN and fallback local bootstrap script and stylesheets

### PR DESCRIPTION
**Pull request by MadhavBahl**
In case of CDN failure, index.html will load stylesheets and scripts locally

### CODE REVIEW

**Comment by superoo7** [comment]
The version is not compatible to current version.
Read `package.json`
``` json
{
    "bootstrap": "4.0.0-beta.2",
    "font-awesome": "^4.7.0",
    "jquery": "^3.2.1",
    "popper.js": "^1.12.5"
}
```


Please use the followings: ([source](http://getbootstrap.com/docs/4.0/getting-started/introduction/))
```html
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.5/umd/popper.min.js" integrity="sha384-vFJXuSJphROIrBnz7yo7oB41mKfc8JzQZiCq4NCceLEaO4IHwicKwpJf9c9IpFgh" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js" integrity="sha384-alpBpkh1PFOepccYVYDB4do5UnbKysX5WZXm3XxPqe5iKTfUKjNkCk9SaVuEZflJ" crossorigin="anonymous"></script>
```

**Comment by MadhavBahl** [comment]
Ok 👍

**Comment by MadhavBahl** [comment]
@superoo7  Done 👍

**Comment by superoo7** [comment]
I'll test out and accept the pr. Thanks for the effort

**Comment by MadhavBahl** [comment]
The pleasure is all mine @superoo7 
I am looking forward for open source contributions.
Tell me if you want any help in any of your projects regarding webdev or IOT 😄 😃

**Comment by superoo7** [comment]
Refer [#7](https://github.com/PhytoMark/bootstrap-starter/pull/7)

**Pull request closed without merging**
